---
language: python
python: "2.7"

sudo: required
dist: trusty

before_install: cd tests

install:
- pip install ansible
- ansible-galaxy install -r roles.yml

script:
- ansible-playbook playbooks/localhost.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
